
spring.application.name=ms-report-async

# Server port (change if needed). Other app uses 8080, so this app uses 8081.
server.port=8081

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin}

# Listener settings
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1

# Retry configuration
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-retries=5
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.amqp.deserialization.trust.all=true

# Template settings
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.template.retry.enabled=true

aws.s3.bucket-trusted=${AWS_S3_BUCKET_TRUSTED:brinks-bucket-trusted}
aws.s3.bucket-client=${AWS_S3_BUCKET_CLIENT:brinks-bucket-client}


# Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false

# Logging
logging.level.root=INFO
logging.level.com.example.ms_report_async=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.amqp=DEBUG
logging.level.software.amazon.awssdk=WARN
logging.file.name=logs/ms-report-async.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

